ciscops/cidrbot

requirements.txt
wxt_cidrbot/cidrbot.py

versions eventually
Initial script can do a few things like interacting between
git and webex and passing the git user name

Added some basic requirements, need to add the

---

cidrbot_run.py
wxt_cidrbot/cidrbot.py

Added a separate script file to run cidrbot.py

Changed cidrbot script to run in "self" completely

---

wxt_cidrbot/cidrbot.py

added functionality for pr messages

Funct re-arrangement to be more understandable

---

wxt_cidrbot/cidrbot.py

Env var set up to work with multiple repos

---

README.md
cidrbot_run.py
wxt_cidrbot/cidrbot.py
wxt_cidrbot/cmd_list.py
wxt_cidrbot/git_api_handler.py

to be part of the cidrbot room to access any bot functionality
Reworked code to handle direct messages and group messages
Added ability to send periodic repo issue lists to group
Removed unnecessary and complicated code logic
Added ability to interact with bot with assign keyword, however
this does not currently have git-sided functionality
Bot responds to "assign" keyword regardless of where user inputs it in
group chat, (both in and out of replies)
Code revamped for obtaining github issue information
+ a few other changes to code architecture made to support future
features

Added user verification for direct messages where user is required

---

requirements.txt
wxt_cidrbot/cidrbot.py
wxt_cidrbot/cmd_list.py
wxt_cidrbot/git_api_handler.py

Added fields (me & username) to list issues function
Added more dictionary fields to scan_repos function
Added better message interpretation
Added ablilty to interact with all bot features through direct messages

Added helpful menu list items

---

README.md
wxt_cidrbot/cidrbot.py
wxt_cidrbot/cmd_list.py
wxt_cidrbot/dynamo_api_handler.py
wxt_cidrbot/git_api_handler.py

- For space moderators Only
Added helpful chat error messages
Removed extra space infront when typing @cidrbot message
vs @cidrbotmessage
Readme updated to reflect changes

Added ability to add and remove from repo pool

---

wxt_cidrbot/cidrbot.py
wxt_cidrbot/cmd_list.py
wxt_cidrbot/dynamo_api_handler.py
wxt_cidrbot/git_api_handler.py

activation to being stored in dynamodb
Re-implemented ability for 'reviewers' to be displayed
when calling list all issues
Added update messages for listing issues for a user

Changed name dictionary from create on every

---

README.md
cloud_formation.yaml

Updated readme to contain deployment instructions

Removed unneeded params in cloud_formation

---

cidrbot_run.py
cloud_formation.yaml

due to webex change on their webhook payload
In cloudformation, changed hanlder to lambda_hanlder
and added necessary / in basegithubpath !sub statement

Json change from to path to rawPath

---

cloud_formation.yaml

Removed unnecessary secruity policy from

---

cidrbot_run.py
cloud_formation.yaml

because aws api v2 doesn't deliver the full webhook path
Removed unneeded env var in cloud formation and added $github
path to stage for github stage

Changed parse to check stage instead of rawPath

---

cidrbot_run.py
cloud_formation.yaml

Changed webhook event parse to match the new stage name

Added github stage

---

cloud_formation.yaml

added dependency for stage and mapping

Fixed capital on $Default

---

README.md
wxt_cidrbot/git_api_handler.py

Added testing for timers note
Added updated way to push lambda layers note
Added note to attach layers to lambda functions

Added more documentation to readme

---

wxt_cidrbot/cidrbot.py

Cidrbot now splits messages up if they exceed a certain limit

Added message overflow checking

---

wxt_cidrbot/cidrbot.py
wxt_cidrbot/cmd_list.py
wxt_cidrbot/dynamo_api_handler.py
wxt_cidrbot/git_api_handler.py
wxt_cidrbot/git_webhook_handler.py

Added moderator controls for name association
Codeowners, triage, manual assigning, weekly reminder message
and list issues, all search for a user based on their gitname

Added gitname<>webexname association in dynamo

---

git_cidrbot/gitauth.py
wxt_cidrbot/dynamo_api_handler.py
wxt_cidrbot/git_webhook_handler.py

In the rooms table, repos are now associated to an installation id and
keys are retrieved and refreshed in a single location in the
installation table

Adding repo > installation id association

---

Makefile
wxt_cidrbot/git_webhook_handler.py

Draft to Normal PR Added

---

wxt_cidrbot/git_webhook_handler.py

Json parse lower for repo names to operate on a conditional

fix:Updating json lower parse
